env = "dev"
app_name = "go-web-template"

[log]
formatter = "json"
level = "debug"
add_source = false

[web]
port = "8080"
read_timeout = 10
write_timeout = 10
idle_timeout = 0
max_header_mb = 1

[db]
name = "postgres"
host = "localhost"
port = 5432
user = "ader"
schema = "postgres"
password = "aderpassword"

[jwt]
access_token_secret = "access_token_secret"
access_token_expiry_hour = 2
refresh_token_secret = "refresh_token_secret"
refresh_token_expiry_hour = 144
